# Generated by Django 2.2 on 2019-05-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('decisions', models.TextField(blank=True)),
                ('decisionDate', models.DateField(auto_now_add=True)),
                ('backgroundInfo', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=256)),
                ('decisionMaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hist.Employee')),
            ],
        ),
    ]
