# Generated by Django 2.2 on 2019-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=256)),
                ('lname', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('decisionDesc', models.TextField(blank=True)),
                ('decisionDate', models.DateField(auto_now_add=True)),
                ('backgroundInfo', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=256)),
                ('impact', models.TextField(blank=True)),
                ('lessonLrnd', models.TextField(blank=True)),
                ('decisionStatus', models.CharField(choices=[('1', 'In-progress'), ('2', 'Completed'), ('3', 'Archived')], default='1', max_length=1)),
                ('decisionMaker', models.ManyToManyField(related_name='decisionMaker', to='hist.Employee')),
                ('enteredby', models.ManyToManyField(related_name='enteredby', to='hist.Employee')),
            ],
        ),
    ]
