# Generated by Django 2.2 on 2019-05-16 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='decisionMaker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hist.Employee'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='subject',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='decision',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
