# Generated by Django 2.2 on 2019-05-26 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='DateLastUpdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decision',
            name='decisionDate',
            field=models.DateField(),
        ),
    ]
