# Generated by Django 2.2 on 2019-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hist', '0003_auto_20190525_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='decisionDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
