# Generated by Django 2.2 on 2019-05-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hist', '0003_auto_20190515_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='decisionMaker',
        ),
        migrations.AddField(
            model_name='decision',
            name='decisionMaker',
            field=models.ManyToManyField(to='hist.Employee'),
        ),
    ]
