# Generated by Django 2.2 on 2019-05-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hist', '0004_auto_20190518_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='decisions',
            new_name='decision',
        ),
        migrations.AddField(
            model_name='decision',
            name='impact',
            field=models.TextField(blank=True),
        ),
    ]
