# Generated by Django 2.2 on 2019-06-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hist', '0004_auto_20190526_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='DateLastUpdate',
        ),
    ]
