# Generated by Django 2.2 on 2019-05-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hist', '0005_auto_20190518_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='decision',
            new_name='decisionDesc',
        ),
    ]
