# Generated by Django 2.2 on 2019-05-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hist', '0006_auto_20190518_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='lname',
        ),
    ]
