# Generated by Django 2.2 on 2019-05-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hist', '0007_auto_20190518_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='lessonLrnd',
            field=models.TextField(blank=True),
        ),
    ]
