# Generated by Django 2.2 on 2019-05-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hist', '0008_decision_lessonlrnd'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='decisionStatus',
            field=models.CharField(choices=[('1', 'In-progress'), ('2', 'Completed'), ('3', 'Archived')], default='1', max_length=1),
        ),
    ]
