# Generated by Django 2.2 on 2019-05-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hist', '0009_decision_decisionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='enteredby',
            field=models.ManyToManyField(related_name='enteredby', to='hist.Employee'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='decisionMaker',
            field=models.ManyToManyField(related_name='decisionMaker', to='hist.Employee'),
        ),
    ]
